import assert from 'node:assert/strict';
import test from 'node:test';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import {
  DEFAULT_CODEX_IMAGE_MODEL,
  DEFAULT_GOD_TIBO_MODEL,
  DEFAULT_IMAGE_PROVIDER,
  DEFAULT_NANO_BANANA_ASPECT_RATIO,
  DEFAULT_NANO_BANANA_IMAGE_SIZE,
  DEFAULT_NANO_BANANA_MODEL,
  IMAGE_PROVIDER_CODEX,
  IMAGE_PROVIDER_GOD_TIBO,
  IMAGE_PROVIDER_NANO_BANANA,
  buildCodexImageApiRequest,
  buildNanoBananaApiRequest,
  extractGeneratedImage,
  getCodexFallbackMessage,
  getNanoBananaFallbackMessage,
  normalizeImageProvider,
  parseNanoBananaCliArgs,
  resolveCodexApiKey,
  resolveNanoBananaApiKey,
  resolveNanoBananaOutputPath,
} from '../../src/nano-banana.js';
import { main, runNanoBananaCli } from '../../scripts/generate-image.js';

test('default image provider is god-tibo', () => {
  assert.equal(DEFAULT_IMAGE_PROVIDER, IMAGE_PROVIDER_GOD_TIBO);
  assert.equal(DEFAULT_GOD_TIBO_MODEL, 'gpt-5.4');
});

test('parseNanoBananaCliArgs applies god-tibo image generation defaults', () => {
  assert.deepEqual(parseNanoBananaCliArgs(['--prompt', 'Foggy mountain road at sunrise']), {
    prompt: 'Foggy mountain road at sunrise',
    slidesDir: 'slides',
    output: '',
    name: '',
    provider: DEFAULT_IMAGE_PROVIDER,
    model: DEFAULT_GOD_TIBO_MODEL,
    aspectRatio: DEFAULT_NANO_BANANA_ASPECT_RATIO,
    imageSize: DEFAULT_NANO_BANANA_IMAGE_SIZE,
    help: false,
  });
});

test('normalizeImageProvider maps aliases to canonical providers', () => {
  assert.equal(normalizeImageProvider('god-tibo'), IMAGE_PROVIDER_GOD_TIBO);
  assert.equal(normalizeImageProvider('GodTibo'), IMAGE_PROVIDER_GOD_TIBO);
  assert.equal(normalizeImageProvider('codex-cli'), IMAGE_PROVIDER_GOD_TIBO);
  assert.equal(normalizeImageProvider('codex'), IMAGE_PROVIDER_CODEX);
  assert.equal(normalizeImageProvider('OpenAI'), IMAGE_PROVIDER_CODEX);
  assert.equal(normalizeImageProvider('nano-banana'), IMAGE_PROVIDER_NANO_BANANA);
  assert.equal(normalizeImageProvider('gemini'), IMAGE_PROVIDER_NANO_BANANA);
});

test('parseNanoBananaCliArgs accepts codex-cli alias and resolves to god-tibo', () => {
  const parsed = parseNanoBananaCliArgs(['--prompt', 'tiny test', '--provider', 'codex-cli']);
  assert.equal(parsed.provider, IMAGE_PROVIDER_GOD_TIBO);
  assert.equal(parsed.model, DEFAULT_GOD_TIBO_MODEL);
});

test('parseNanoBananaCliArgs accepts openai alias and resolves to codex', () => {
  const parsed = parseNanoBananaCliArgs(['--prompt', 'tiny test', '--provider', 'openai']);
  assert.equal(parsed.provider, IMAGE_PROVIDER_CODEX);
  assert.equal(parsed.model, DEFAULT_CODEX_IMAGE_MODEL);
});

test('parseNanoBananaCliArgs reads explicit options and rejects invalid values', () => {
  assert.deepEqual(
    parseNanoBananaCliArgs([
      '--prompt=Industrial robot arm in a dark studio',
      '--slides-dir',
      'decks/demo',
      '--output',
      'decks/demo/assets/robot-hero',
      '--name',
      'robot-hero',
      '--provider',
      'nano-banana',
      '--model',
      'gemini-3-pro-image-preview',
      '--aspect-ratio',
      '1:1',
      '--image-size',
      '2K',
    ]),
    {
      prompt: 'Industrial robot arm in a dark studio',
      slidesDir: 'decks/demo',
      output: 'decks/demo/assets/robot-hero',
      name: 'robot-hero',
      provider: 'nano-banana',
      model: 'gemini-3-pro-image-preview',
      aspectRatio: '1:1',
      imageSize: '2K',
      help: false,
    },
  );

  assert.throws(() => parseNanoBananaCliArgs([]), /--prompt must be a non-empty string/i);
  assert.throws(() => parseNanoBananaCliArgs(['--prompt', 'x', '--image-size', '8K']), /unknown --image-size/i);
  assert.throws(() => parseNanoBananaCliArgs(['--prompt', 'x', '--provider', 'banana']), /unknown --provider/i);
});

test('main routes to god-tibo by default and writes the generated bytes into slides/assets', async () => {
  const { mkdtemp, readFile, rm } = await import('node:fs/promises');
  const os = await import('node:os');
  const path = await import('node:path');
  const workspace = await mkdtemp(path.join(os.tmpdir(), 'godtibo-default-test-'));
  const calls = [];
  const output = [];

  try {
    await runNanoBananaCli(
      ['--prompt', 'Studio portrait of a founder with warm rim light', '--slides-dir', workspace, '--aspect-ratio', '1:1'],
      {
        env: {},
        fetchImpl: async () => {
          throw new Error('fetch must not be called when god-tibo runs successfully');
        },
        stdout: { write(chunk) { output.push(String(chunk)); } },
        generateGodTiboImageImpl: async (args) => {
          calls.push(args);
          return {
            mimeType: 'image/png',
            bytes: Buffer.from('god-tibo-bytes'),
            mode: 'live',
            warnings: [],
            revisedPrompt: null,
          };
        },
      },
    );

    assert.equal(calls.length, 1);
    assert.equal(calls[0].prompt, 'Studio portrait of a founder with warm rim light');
    assert.equal(calls[0].aspectRatio, '1:1');
    assert.equal(calls[0].model, DEFAULT_GOD_TIBO_MODEL);

    const written = await readFile(path.join(workspace, 'assets', 'god-tibo-studio-portrait-of-a-founder-with-warm-rim-light.png'));
    assert.equal(written.toString(), 'god-tibo-bytes');
    assert.match(output.join(''), /Image provider: god-tibo/);
    assert.match(output.join(''), /\.\/assets\/god-tibo-studio-portrait-of-a-founder-with-warm-rim-light\.png/);
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('main falls back to codex/openai when god-tibo throws and OPENAI_API_KEY is set', async () => {
  const { mkdtemp, readFile, rm } = await import('node:fs/promises');
  const os = await import('node:os');
  const path = await import('node:path');
  const workspace = await mkdtemp(path.join(os.tmpdir(), 'godtibo-codex-fallback-'));
  const fetchCalls = [];
  const output = [];

  try {
    await runNanoBananaCli(
      ['--prompt', 'A floating product render', '--slides-dir', workspace],
      {
        env: { OPENAI_API_KEY: 'sk-test' },
        fetchImpl: async (url, init) => {
          fetchCalls.push({ url, init });
          return {
            ok: true,
            status: 200,
            async json() {
              return { data: [{ b64_json: Buffer.from('codex-fallback-bytes').toString('base64') }] };
            },
          };
        },
        stdout: { write(chunk) { output.push(String(chunk)); } },
        generateGodTiboImageImpl: async () => {
          const err = new Error('Unauthorized from private Codex backend.');
          err.code = 'UNAUTHORIZED';
          throw err;
        },
      },
    );

    assert.equal(fetchCalls.length, 1);
    assert.equal(fetchCalls[0].url, 'https://api.openai.com/v1/images/generations');
    assert.equal(fetchCalls[0].init.headers.Authorization, 'Bearer sk-test');

    const written = await readFile(path.join(workspace, 'assets', 'codex-a-floating-product-render.png'));
    assert.equal(written.toString(), 'codex-fallback-bytes');
    assert.match(output.join(''), /Fallback: god-tibo failed/);
    assert.match(output.join(''), /Image provider: codex/);
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('main falls back to nano-banana when god-tibo fails and only GOOGLE_API_KEY is set', async () => {
  const { mkdtemp, readFile, rm } = await import('node:fs/promises');
  const os = await import('node:os');
  const path = await import('node:path');
  const workspace = await mkdtemp(path.join(os.tmpdir(), 'godtibo-nano-fallback-'));
  const fetchCalls = [];
  const output = [];

  try {
    await runNanoBananaCli(
      ['--prompt', 'A serene seascape', '--slides-dir', workspace],
      {
        env: { GOOGLE_API_KEY: 'goog-test' },
        fetchImpl: async (url, init) => {
          fetchCalls.push({ url, init });
          return {
            ok: true,
            status: 200,
            async json() {
              return {
                candidates: [
                  {
                    content: {
                      parts: [
                        {
                          inlineData: {
                            mimeType: 'image/png',
                            data: Buffer.from('nano-fallback-bytes').toString('base64'),
                          },
                        },
                      ],
                    },
                  },
                ],
              };
            },
          };
        },
        stdout: { write(chunk) { output.push(String(chunk)); } },
        generateGodTiboImageImpl: async () => {
          throw new Error('Boom from god-tibo.');
        },
      },
    );

    assert.equal(fetchCalls.length, 1);
    assert.match(fetchCalls[0].url, /models\/gemini-3-pro-image-preview:generateContent$/);
    const written = await readFile(path.join(workspace, 'assets', 'nano-banana-a-serene-seascape.png'));
    assert.equal(written.toString(), 'nano-fallback-bytes');
    assert.match(output.join(''), /Image provider: nano-banana/);
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('main throws an actionable god-tibo fallback error when no fallback credentials are configured', async () => {
  await assert.rejects(
    () => runNanoBananaCli(
      ['--prompt', 'a tiny test'],
      {
        env: {},
        fetchImpl: async () => {
          throw new Error('fetch should not be called');
        },
        stdout: { write() {} },
        generateGodTiboImageImpl: async () => {
          throw new Error('god-tibo offline.');
        },
      },
    ),
    /codex login/,
  );
});

test('resolveCodexApiKey reads OPENAI_API_KEY for the default provider', () => {
  assert.deepEqual(resolveCodexApiKey({ OPENAI_API_KEY: 'openai-key' }), {
    apiKey: 'openai-key',
    source: 'OPENAI_API_KEY',
  });
  assert.deepEqual(resolveCodexApiKey({ OPENAI_API_KEY: '  ' }), {
    apiKey: '',
    source: '',
  });
});

test('resolveNanoBananaApiKey prefers GOOGLE_API_KEY and falls back to GEMINI_API_KEY', () => {
  assert.deepEqual(resolveNanoBananaApiKey({ GOOGLE_API_KEY: 'google-key', GEMINI_API_KEY: 'gemini-key' }), {
    apiKey: 'google-key',
    source: 'GOOGLE_API_KEY',
  });
  assert.deepEqual(resolveNanoBananaApiKey({ GEMINI_API_KEY: 'gemini-key' }), {
    apiKey: 'gemini-key',
    source: 'GEMINI_API_KEY',
  });
  assert.deepEqual(resolveNanoBananaApiKey({}), {
    apiKey: '',
    source: '',
  });
});

test('resolveNanoBananaOutputPath keeps generated assets under the deck assets directory', () => {
  const target = resolveNanoBananaOutputPath({
    slidesDir: path.resolve('decks/demo'),
    prompt: 'A bright banana hovering over a keynote stage',
    output: '',
    name: '',
    mimeType: 'image/png',
  });

  assert.match(target.outputPath, /decks\/demo\/assets\/nano-banana-a-bright-banana-hovering-over-a-keynote-stage\.png$/);
  assert.equal(target.relativeRef, './assets/nano-banana-a-bright-banana-hovering-over-a-keynote-stage.png');

  assert.throws(
    () => resolveNanoBananaOutputPath({
      slidesDir: path.resolve('decks/demo'),
      prompt: 'test',
      output: path.resolve('decks/outside.png'),
      mimeType: 'image/png',
    }),
    /must be saved inside .*assets/i,
  );
});

test('resolveNanoBananaOutputPath preserves explicit cwd-relative deck asset paths', () => {
  const target = resolveNanoBananaOutputPath({
    slidesDir: path.resolve('decks/demo'),
    prompt: 'test',
    output: 'decks/demo/assets/robot-hero',
    mimeType: 'image/png',
  });

  assert.match(target.outputPath, /decks\/demo\/assets\/robot-hero\.png$/);
  assert.equal(target.relativeRef, './assets/robot-hero.png');
});

test('resolveNanoBananaOutputPath treats relative --output values as assets-relative paths', () => {
  const slidesDir = path.resolve('decks/demo');
  const target = resolveNanoBananaOutputPath({
    slidesDir,
    prompt: 'test',
    output: 'hero-image',
    mimeType: 'image/png',
  });

  assert.equal(target.outputPath, path.join(slidesDir, 'assets', 'hero-image.png'));
  assert.equal(target.relativeRef, './assets/hero-image.png');
});

test('resolveNanoBananaOutputPath treats assets-prefixed relative output values as assets-relative paths', () => {
  const slidesDir = path.resolve('decks/demo');
  const target = resolveNanoBananaOutputPath({
    slidesDir,
    prompt: 'test',
    output: 'assets/hero-image',
    mimeType: 'image/png',
  });

  assert.equal(target.outputPath, path.join(slidesDir, 'assets', 'hero-image.png'));
  assert.equal(target.relativeRef, './assets/hero-image.png');
});

test('resolveNanoBananaOutputPath keeps nested asset-relative output values inside assets', () => {
  const slidesDir = path.resolve('decks/demo');
  const target = resolveNanoBananaOutputPath({
    slidesDir,
    prompt: 'test',
    output: 'nested/hero-image',
    mimeType: 'image/png',
  });

  assert.equal(target.outputPath, path.join(slidesDir, 'assets', 'nested', 'hero-image.png'));
  assert.equal(target.relativeRef, './assets/nested/hero-image.png');
});

test('buildCodexImageApiRequest maps slide aspect ratios to supported OpenAI landscape sizes', () => {
  assert.deepEqual(
    buildCodexImageApiRequest({
      prompt: 'Generate a premium fintech dashboard hero image.',
      model: DEFAULT_CODEX_IMAGE_MODEL,
      aspectRatio: '16:9',
    }),
    {
      model: DEFAULT_CODEX_IMAGE_MODEL,
      prompt: 'Generate a premium fintech dashboard hero image.',
      size: '1536x1024',
    },
  );

  assert.deepEqual(
    buildCodexImageApiRequest({
      prompt: 'Generate a square app icon.',
      model: DEFAULT_CODEX_IMAGE_MODEL,
      aspectRatio: '1:1',
    }),
    {
      model: DEFAULT_CODEX_IMAGE_MODEL,
      prompt: 'Generate a square app icon.',
      size: '1024x1024',
    },
  );
});

test('buildNanoBananaApiRequest matches the documented Gemini image request shape', () => {
  assert.deepEqual(
    buildNanoBananaApiRequest({
      prompt: 'Generate a premium fintech dashboard hero image.',
      aspectRatio: '16:9',
      imageSize: '4K',
    }),
    {
      contents: [
        {
          parts: [{ text: 'Generate a premium fintech dashboard hero image.' }],
        },
      ],
      generationConfig: {
        imageConfig: {
          aspectRatio: '16:9',
          imageSize: '4K',
        },
      },
    },
  );
});

test('extractGeneratedImage returns the first inline image part', () => {
  const payload = extractGeneratedImage({
    candidates: [
      {
        content: {
          parts: [
            { text: 'drafted image' },
            {
              inlineData: {
                mimeType: 'image/png',
                data: Buffer.from('png-bytes').toString('base64'),
              },
            },
          ],
        },
      },
    ],
  });

  assert.equal(payload.mimeType, 'image/png');
  assert.equal(Buffer.from(payload.bytes).toString(), 'png-bytes');
});

test('getCodexFallbackMessage includes API key, Nano Banana fallback, and web search guidance', () => {
  const message = getCodexFallbackMessage('Missing API key.');
  assert.match(message, /OPENAI_API_KEY/i);
  assert.match(message, /GOOGLE_API_KEY|GEMINI_API_KEY/i);
  assert.match(message, /web search/i);
  assert.match(message, /\.\/assets\//);
});

test('getNanoBananaFallbackMessage tells the agent to ask for a key or fall back to web search', () => {
  assert.match(
    getNanoBananaFallbackMessage('Missing API key.'),
    /GOOGLE_API_KEY|GEMINI_API_KEY/i,
  );
  assert.match(
    getNanoBananaFallbackMessage('Missing API key.'),
    /Nano Banana/i,
  );
  assert.match(
    getNanoBananaFallbackMessage('Missing API key.'),
    /\.\/assets\//,
  );
});

test('main with explicit --provider codex generates Codex image into slides/assets', async () => {
  const workspace = await mkdtemp(path.join(os.tmpdir(), 'codex-image-test-'));
  const output = [];
  const calls = [];

  try {
    await main(
      ['--prompt', 'Studio portrait of a founder with warm rim light', '--slides-dir', workspace, '--provider', 'codex'],
      {
        env: { OPENAI_API_KEY: 'test-key' },
        fetchImpl: async (url, init) => {
          calls.push({ url, init });
          return {
            ok: true,
            status: 200,
            async json() {
              return {
                data: [
                  {
                    b64_json: Buffer.from('fake-image-bytes').toString('base64'),
                  },
                ],
              };
            },
          };
        },
        stdout: {
          write(chunk) {
            output.push(String(chunk));
          },
        },
      },
    );

    assert.equal(calls.length, 1);
    assert.equal(calls[0].url, 'https://api.openai.com/v1/images/generations');
    assert.equal(calls[0].init.headers.Authorization, 'Bearer test-key');
    const requestBody = JSON.parse(calls[0].init.body);
    assert.equal(requestBody.model, DEFAULT_CODEX_IMAGE_MODEL);
    assert.equal(requestBody.prompt, 'Studio portrait of a founder with warm rim light');
    assert.equal(requestBody.size, '1536x1024');

    const assetDir = path.join(workspace, 'assets');
    const files = await readFile(path.join(assetDir, 'codex-studio-portrait-of-a-founder-with-warm-rim-light.png'));
    assert.equal(files.toString(), 'fake-image-bytes');
    assert.match(output.join(''), /\.\/assets\/codex-studio-portrait-of-a-founder-with-warm-rim-light\.png/);
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('main maps explicit square aspect ratio to OpenAI square size when provider=codex', async () => {
  const workspace = await mkdtemp(path.join(os.tmpdir(), 'codex-image-square-test-'));
  const calls = [];

  try {
    await main(
      ['--prompt', 'A centered product icon', '--slides-dir', workspace, '--aspect-ratio', '1:1', '--provider', 'codex'],
      {
        env: { OPENAI_API_KEY: 'test-key' },
        fetchImpl: async (url, init) => {
          calls.push({ url, init });
          return {
            ok: true,
            status: 200,
            async json() {
              return { data: [{ b64_json: Buffer.from('square-image-bytes').toString('base64') }] };
            },
          };
        },
        stdout: { write() {} },
      },
    );

    assert.equal(JSON.parse(calls[0].init.body).size, '1024x1024');
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('main with --provider codex rejects --image-size because it is Nano Banana only', async () => {
  await assert.rejects(
    () => main(
      ['--prompt', 'A floating product render', '--image-size', '2K', '--provider', 'codex'],
      {
        env: { OPENAI_API_KEY: 'test-key' },
        fetchImpl: async () => {
          throw new Error('fetch should not be called');
        },
      },
    ),
    /--image-size.*Nano Banana/i,
  );
});

test('main with --provider codex falls back to Nano Banana when OPENAI_API_KEY is unavailable but GOOGLE_API_KEY is configured', async () => {
  const workspace = await mkdtemp(path.join(os.tmpdir(), 'codex-image-fallback-test-'));
  const calls = [];

  try {
    await main(
      ['--prompt', 'A floating product render', '--slides-dir', workspace, '--provider', 'codex'],
      {
        env: { GOOGLE_API_KEY: 'google-key' },
        fetchImpl: async (url, init) => {
          calls.push({ url, init });
          return {
            ok: true,
            status: 200,
            async json() {
              return {
                candidates: [
                  {
                    content: {
                      parts: [
                        {
                          inlineData: {
                            mimeType: 'image/png',
                            data: Buffer.from('fallback-image-bytes').toString('base64'),
                          },
                        },
                      ],
                    },
                  },
                ],
              };
            },
          };
        },
        stdout: { write() {} },
      },
    );

    assert.equal(calls.length, 1);
    assert.match(calls[0].url, /models\/gemini-3-pro-image-preview:generateContent$/);
    const files = await readFile(path.join(workspace, 'assets', 'nano-banana-a-floating-product-render.png'));
    assert.equal(files.toString(), 'fallback-image-bytes');
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('main with --provider codex throws an actionable fallback error when no API key is configured', async () => {
  await assert.rejects(
    () => main(['--prompt', 'A floating product render', '--provider', 'codex'], { env: {}, fetchImpl: async () => {
      throw new Error('fetch should not be called');
    } }),
    /OPENAI_API_KEY/i,
  );
});

test('main with --provider nano-banana hits the Gemini endpoint and writes the deck-local PNG', async () => {
  const workspace = await mkdtemp(path.join(os.tmpdir(), 'nano-direct-happy-test-'));
  const fetchCalls = [];
  const stdoutChunks = [];

  try {
    await main(
      ['--prompt', 'A floating product render', '--slides-dir', workspace, '--provider', 'nano-banana', '--image-size', '4K'],
      {
        env: { GOOGLE_API_KEY: 'goog-direct-key' },
        fetchImpl: async (url, init) => {
          fetchCalls.push({ url, init });
          return {
            ok: true,
            status: 200,
            async json() {
              return {
                candidates: [
                  {
                    content: {
                      parts: [
                        {
                          inlineData: {
                            mimeType: 'image/png',
                            data: Buffer.from('nano-direct-bytes').toString('base64'),
                          },
                        },
                      ],
                    },
                  },
                ],
              };
            },
          };
        },
        stdout: { write(chunk) { stdoutChunks.push(String(chunk)); } },
      },
    );

    assert.equal(fetchCalls.length, 1);
    assert.match(fetchCalls[0].url, /models\/gemini-3-pro-image-preview:generateContent$/);
    assert.equal(fetchCalls[0].init.headers['x-goog-api-key'], 'goog-direct-key');
    const body = JSON.parse(fetchCalls[0].init.body);
    assert.equal(body.contents[0].parts[0].text, 'A floating product render');
    assert.equal(body.generationConfig.imageConfig.imageSize, '4K');
    const written = await readFile(path.join(workspace, 'assets', 'nano-banana-a-floating-product-render.png'));
    assert.equal(written.toString(), 'nano-direct-bytes');
    assert.match(stdoutChunks.join(''), /Image provider: nano-banana/);
  } finally {
    await rm(workspace, { recursive: true, force: true });
  }
});

test('main with --provider codex wraps network failures in the actionable Nano Banana fallback guidance', async () => {
  await assert.rejects(
    () => main(
      ['--prompt', 'A floating product render', '--provider', 'codex'],
      {
        env: { OPENAI_API_KEY: 'test-key' },
        fetchImpl: async () => {
          throw new Error('network down');
        },
      },
    ),
    /Nano Banana/i,
  );
});
